name: Test action

on:
  workflow_dispatch:

jobs:
  sayHello:
    runs-on: testrunner
    steps:
      - name: Say hello
        run:  |
          echo "Hello world"
          for i in {1..1000000}; do echo $i; done
          sleep 100
          
